[package]
name = "aoc"
version = "0.1.0"
authors = ["George Mocanu <mocanu.geo98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day01"
path = "src/day01.rs"
